name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RO_ACCESS_KEY }}
          submodules: true
      - name: Set up docker-compose port to listen ssl traffic
        run: echo -e "NGINX_SERVER_NAME=${{ secrets.NGINX_SERVER_NAME }}\nHOST_HTTP_PORT=${{ secrets.HOST_HTTP_PORT }}" > .env
      - name: Pulling available images
        run: docker-compose -f docker-compose.yml pull
      - name: Building images
        run: docker-compose -f docker-compose.yml build
      - name: Up new containers
        run: docker-compose -f docker-compose.yml up -d
